mango_sylius_contact_form_shop_account_message_index:
  path: /messages
  methods: [GET]
  defaults:
    _controller: sylius.controller.shop_user:indexAction
    _sylius:
      section: shop_account
      template: "@MangoSyliusContactFormPlugin/ContactForm/Account/Index.html.twig"
      grid: mango_sylius_account_contact_message


mango_sylius_contact_form_account_answer_send:
  path: messages/{id}/send
  methods: [POST]
  defaults:
    _controller: MangoSylius\SyliusContactFormPlugin\Controller\ContactFormController:accountAnswerMessage

mango_sylius_contact_form_shop_account_message_show:
  path: messages/{id}
  methods: [GET]
  defaults:
    _controller: MangoSylius\SyliusContactFormPlugin\Controller\ContactFormController:showAccountMessageAction
