mango_sylius_admin_contact_show:
  path: /contact/show/{id}
  defaults:
    _controller: MangoSylius\SyliusContactFormPlugin\Controller\ContactFormController:showMessageAction

mango_sylius_contact_form_answer_send:
  path: contactform/{id}/send
  methods: [POST]
  defaults:
    _controller: MangoSylius\SyliusContactFormPlugin\Controller\ContactFormController:answerMessage

mango_sylius_admin_contact_message:
  resource: |
    alias: mango_contact_form_plugin.message
    section: admin
    templates: SyliusAdminBundle:Crud
    except: ['show']
    redirect: update
    grid: mango_sylius_admin_contact_message
    vars:
        all:
            subheader: mango_sylius.contactForm.ui.subtitle
            header: mango_sylius.contactForm.ui.title
        index:
            icon: 'comments'
  type: sylius.resource