imports:
  - { resource: "@MangoSyliusContactFormPlugin/Resources/config/ressources.yml" }
  - { resource: "@MangoSyliusContactFormPlugin/Resources/config/mailer.yml" }
  - { resource: "@MangoSyliusContactFormPlugin/Resources/config/grid.yml" }