sylius_resource:
  resources:
    mango_contact_form_plugin.message:
      classes:
        model: MangoSylius\ContactFormPlugin\Entity\ContactFormMessage
        form: MangoSylius\ContactFormPlugin\Form\Type\ContactFormType
        repository: MangoSylius\ContactFormPlugin\Repository\ContactMessageRepository
