sylius_resource:
  resources:
    mango_contact_form_plugin.contact_form_message:
      classes:
        model: MangoSylius\SyliusContactFormPlugin\Entity\ContactFormMessage
        form: MangoSylius\SyliusContactFormPlugin\Form\Type\ContactFormType

