services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  MangoSylius\SyliusContactFormPlugin\Service\ContactFormSettingsProvider: ~

  MangoSylius\SyliusContactFormPlugin\Form\Type\ContactFormType:
    tags:
      - { name: form.type }
    arguments:
      $contactFormSettings: '@MangoSylius\SyliusContactFormPlugin\Service\ContactFormSettingsProvider'

  MangoSylius\SyliusContactFormPlugin\Menu\ContactMenuBuilder:
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: buildMenu }

  MangoSylius\SyliusContactFormPlugin\Controller\ContactFormController:
    tags:
      - { name: controller.service_arguments }
    arguments:
      $contactFormSettings: '@MangoSylius\SyliusContactFormPlugin\Service\ContactFormSettingsProvider'
      $translator: '@translator'
      $templatingEngine: '@templating'
      $entityManager: '@doctrine.orm.entity_manager'
      $mailer: '@sylius.email_sender'
      $router: '@router'
      $flashBag: '@session.flash_bag'
      $builder: '@form.factory'
      $adminUserRepository: '@sylius.repository.admin_user'
      $channelContext: '@sylius.context.channel'
      $contactFormRepository: '@mango_contact_form_plugin.repository.message'
      $tokenStorage: '@security.token_storage'
      $recaptchaPublic: '%env(string:CONTACT_FORM_RECAPTCHA_PUBLIC_KEY)%'
      $recaptchaSecret: '%env(string:CONTACT_FORM_RECAPTCHA_SECRET_KEY)%'






