services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    MangoSylius\SyliusContactFormPlugin\Form\Type\ContactFormType:
        tags:
            - { name: form.type }

    MangoSylius\SyliusContactFormPlugin\Controller\ContactFormController:
        tags:
            - { name: controller.service_arguments }
        arguments:
            $router: '@router'
            $flashBag: '@session.flash_bag'
            $translator: '@translator'
            $entityManager: '@doctrine.orm.entity_manager'
            $templatingEngine: '@templating'
            $builder: '@form.factory'